export const swiperSlides = [
  {
    id: 1,
    progressColor: '#553d36',
    bgColor: '#ffffff',
    subTitle: 'OUR PURPOSE',
    title: 'BLUE WAVE ZONE',
    description: 'Extract beneficial bacteria from pure soil to foster innovative practices in agriculture, drive sustainability in industry, and facilitate breakthroughs in medical sciences.',
    buttonColor: '#553d36',
    ghostName: 'Blue Wave Zone',
    ghostTitle: 'Biotech Innovation',
    infoColor: '#553d36',
    portfolio: 'bluewavezone',
  },
  {
    id: 2,
    progressColor: '#1a1a1a',
    bgColor: '#000000',
    subTitle: 'CHATBOT DEVELOPMENT',
    title: 'CHATSPEAR',
    description: 'Building intelligent bots that work 24/7. Custom chatbots, GPT creation, and voice agents that boost customer service to superhero levels.',
    buttonColor: '#1a1a1a',
    ghostName: 'Chatspear',
    ghostTitle: 'Bot Builders',
    infoColor: '#1a1a1a',
    portfolio: 'chatsphear',
  },
  {
    id: 3,
    progressColor: '#f58327',
    bgColor: '#f58327',
    subTitle: 'BOTS & LEADS',
    title: 'GROWITHUS',
    description: 'Leading experts in bot building, web development, and lead generation. Want more qualified leads starting now? 50+ 5-star reviews.',
    buttonColor: '#f58327',
    ghostName: 'Growithus',
    ghostTitle: 'Bot Experts',
    infoColor: '#f58327',
    portfolio: 'growithus',
  },
  {
    id: 4,
    progressColor: '#f25c05',
    bgColor: '#f58327',
    subTitle: 'FEWER TAPS MORE JOBS',
    title: 'FROM LEAD TO PAID',
    description: 'Skip the admin. Ship quotes, schedule fast, keep the bakkie moving. Built for SA conditions—works offline, perfect for load shedding.',
    buttonColor: '#f25c05',
    ghostName: 'OnSite',
    ghostTitle: 'Business Simplified',
    infoColor: '#f25c05',
    portfolio: 'onsite',
  },
  {
    id: 5,
    progressColor: '#1875ff',
    bgColor: '#ffffff',
    subTitle: 'COMPREHENSIVE SOLUTIONS',
    title: 'FINANCIAL SERVICES',
    description: 'Comprehensive financial and insurance solutions across South Africa. Serving SMEs with professionalism and integrity in all interactions.',
    buttonColor: '#1875ff',
    ghostName: 'Solutions Provider',
    ghostTitle: 'Trusted Advisor',
    infoColor: '#1875ff',
    portfolio: 'worksitesolutions',
  },
  {
    id: 6,
    progressColor: '#22c55e',
    bgColor: '#00cc00',
    subTitle: 'BE SEEN SHOW & SELL',
    title: 'A2Z SELLR',
    description: 'The all-in-one home for South African sellers. Your products, your services, your brand—amplified with tools built for real SA businesses. Boost revenue by 80%.',
    buttonColor: '#22c55e',
    ghostName: 'A2Z Sellr',
    ghostTitle: 'Seller Platform',
    infoColor: '#22c55e',
    portfolio: 'a2zsellr',
  },
  {
    id: 7,
    progressColor: '#16a34a',
    bgColor: '#ffffff',
    subTitle: 'HEALTH & WELLNESS',
    title: 'DAY1 HEALTH',
    description: 'Personalized health solutions designed to help you achieve your wellness goals. Expert guidance, proven results, and lasting change.',
    buttonColor: '#16a34a',
    ghostName: 'Day1 Health',
    ghostTitle: 'Wellness Platform',
    infoColor: '#16a34a',
    portfolio: 'day1health',
  },
  {
    id: 8,
    progressColor: '#b48b49',
    bgColor: '#ffffff',
    subTitle: 'COMMUNITY PLATFORM',
    title: 'KHAMBI',
    description: 'Connect, collaborate, and grow together. A vibrant community platform bringing people together for meaningful interactions and shared experiences.',
    buttonColor: '#b48b49',
    ghostName: 'Khambi',
    ghostTitle: 'Community Hub',
    infoColor: '#b48b49',
    portfolio: 'khambi',
  },
  {
    id: 9,
    progressColor: '#3a9e92',
    bgColor: '#ffffff',
    subTitle: 'INNOVATION PLATFORM',
    title: 'EUBIOSIS',
    description: 'Cutting-edge solutions for modern challenges. Eubiosis brings innovation and clarity to complex problems with elegant, user-focused design.',
    buttonColor: '#3a9e92',
    ghostName: 'Eubiosis',
    ghostTitle: 'Innovation Hub',
    infoColor: '#3a9e92',
    portfolio: 'eubiosis',
  },
]
