export const swiperSlides = [
  {
    id: 1,
    progressColor: '#ff6600',
    bgColor: '#ffffff',
    subTitle: 'OUR PURPOSE',
    title: 'BLUE WAVE ZONE',
    description: 'Beneficial bacteria from pure soil driving innovation in agriculture, sustainability, and medicine.',
    buttonColor: '#553d36',
    ghostName: 'Blue Wave Zone',
    ghostTitle: 'Biotech Innovation',
    infoColor: '#553d36',
    portfolio: 'bluewavezone',
    url: 'https://bluewavezone.co.za/',
  },
  {
    id: 2,
    progressColor: '#ff6600',
    bgColor: '#000000',
    subTitle: 'CHATBOT DEVELOPMENT',
    title: 'CHATSPEAR',
    description: '24/7 intelligent bots. Custom chatbots, GPT creation, and voice agents.',
    buttonColor: '#1a1a1a',
    ghostName: 'Chatspear',
    ghostTitle: 'Bot Builders',
    infoColor: '#1a1a1a',
    portfolio: 'chatsphear',
    url: 'https://chatsphearsolutions.framer.website/',
  },
  {
    id: 3,
    progressColor: '#ff6600',
    bgColor: '#f58327',
    subTitle: 'BOTS & LEADS',
    title: 'GROWITHUS',
    description: 'Expert bot building, web development, and lead generation. 50+ 5-star reviews.',
    buttonColor: '#f58327',
    ghostName: 'Growithus',
    ghostTitle: 'Bot Experts',
    infoColor: '#f58327',
    portfolio: 'growithus',
    url: 'https://growithus11.framer.website/',
  },
  {
    id: 4,
    progressColor: '#ff6600',
    bgColor: '#f58327',
    subTitle: 'FEWER TAPS MORE JOBS',
    title: 'FROM LEAD TO PAID',
    description: 'Skip admin. Ship quotes, schedule fast. Built for SA—works offline.',
    buttonColor: '#f25c05',
    ghostName: 'OnSite',
    ghostTitle: 'Business Simplified',
    infoColor: '#f25c05',
    portfolio: 'onsite',
    url: 'https://onsite-theta.vercel.app/',
  },
  {
    id: 5,
    progressColor: '#ff6600',
    bgColor: '#ffffff',
    subTitle: 'COMPREHENSIVE SOLUTIONS',
    title: 'FINANCIAL SERVICES',
    description: 'Financial and insurance solutions across South Africa. Professional service with integrity.',
    buttonColor: '#1875ff',
    ghostName: 'WorkSite Solutions',
    ghostTitle: 'Insurance & More',
    infoColor: '#1875ff',
    portfolio: 'worksitesolutions',
    url: 'https://worksitesolutions.vercel.app/',
  },
  {
    id: 6,
    progressColor: '#ff6600',
    bgColor: '#00cc00',
    subTitle: 'BE SEEN SHOW & SELL',
    title: 'A2Z SELLR',
    description: 'All-in-one platform for SA sellers. Amplify your brand. Boost revenue by 80%.',
    buttonColor: '#22c55e',
    ghostName: 'A2Z Sellr',
    ghostTitle: 'Seller Platform',
    infoColor: '#22c55e',
    portfolio: 'a2zsellr',
    url: 'https://www.a2zsellr.life/',
  },
  {
    id: 7,
    progressColor: '#ff6600',
    bgColor: '#ffffff',
    subTitle: 'HEALTHCARE THAT WORKS',
    title: 'DAY1 HEALTH',
    description: 'Quality healthcare for South Africans. Apply in 5 minutes. Cover starts Day 1.',
    buttonColor: '#16a34a',
    ghostName: 'Day1 Health',
    ghostTitle: 'Healthcare Coverage',
    infoColor: '#16a34a',
    portfolio: 'day1health',
    url: 'https://www.day1health.co.za/',
  },
  {
    id: 8,
    progressColor: '#ff6600',
    bgColor: '#ffffff',
    subTitle: 'DIGNIFIED SERVICES',
    title: 'KHAMBI',
    description: 'Compassionate, affordable funeral services honoring your loved ones with dignity.',
    buttonColor: '#b48b49',
    ghostName: 'Khambi',
    ghostTitle: 'Funeral Services',
    infoColor: '#b48b49',
    portfolio: 'khambi',
    url: 'https://khambifunerals.com/',
  },
  {
    id: 9,
    progressColor: '#ff6600',
    bgColor: '#ffffff',
    subTitle: 'NATURAL GUT HEALTH',
    title: 'EUBIOSIS-S',
    description: 'Gut health results. 42 beneficial bacterial strains in pure organic honey.',
    buttonColor: '#3a9e92',
    ghostName: 'Eubiosis-S',
    ghostTitle: 'Gut Health Supplement',
    infoColor: '#3a9e92',
    portfolio: 'eubiosis',
    url: 'https://www.eubiosis.pro/',
  },
  {
    id: 10,
    progressColor: '#ff6600',
    bgColor: '#000000',
    subTitle: 'HONEST CAR DEALERSHIP',
    title: 'MAJESTIC CARS',
    description: 'Honest, stress-free car buying. 100% inspected vehicles. Fair pricing, transparent service.',
    buttonColor: '#ff8c00',
    ghostName: 'Majestic Cars',
    ghostTitle: 'Modern Dealership',
    infoColor: '#ff8c00',
    portfolio: 'majestic-cars',
    url: 'https://majesticars.com/',
  },
]
