export const swiperSlides = [
  {
    id: 1,
    progressColor: '#ff6600',
    bgColor: '#ffffff',
    subTitle: 'OUR PURPOSE',
    title: 'BLUE WAVE ZONE',
    description: 'Extract beneficial bacteria from pure soil to foster innovative practices in agriculture, drive sustainability in industry, and facilitate breakthroughs in medical sciences.',
    buttonColor: '#553d36',
    ghostName: 'Blue Wave Zone',
    ghostTitle: 'Biotech Innovation',
    infoColor: '#553d36',
    portfolio: 'bluewavezone',
    url: 'https://bluewavezone.co.za/',
  },
  {
    id: 2,
    progressColor: '#ff6600',
    bgColor: '#000000',
    subTitle: 'CHATBOT DEVELOPMENT',
    title: 'CHATSPEAR',
    description: 'Building intelligent bots that work 24/7. Custom chatbots, GPT creation, and voice agents that boost customer service to superhero levels.',
    buttonColor: '#1a1a1a',
    ghostName: 'Chatspear',
    ghostTitle: 'Bot Builders',
    infoColor: '#1a1a1a',
    portfolio: 'chatsphear',
    url: 'https://chatsphearsolutions.framer.website/',
  },
  {
    id: 3,
    progressColor: '#ff6600',
    bgColor: '#f58327',
    subTitle: 'BOTS & LEADS',
    title: 'GROWITHUS',
    description: 'Leading experts in bot building, web development, and lead generation. Want more qualified leads starting now? 50+ 5-star reviews.',
    buttonColor: '#f58327',
    ghostName: 'Growithus',
    ghostTitle: 'Bot Experts',
    infoColor: '#f58327',
    portfolio: 'growithus',
    url: 'https://growithus11.framer.website/',
  },
  {
    id: 4,
    progressColor: '#ff6600',
    bgColor: '#f58327',
    subTitle: 'FEWER TAPS MORE JOBS',
    title: 'FROM LEAD TO PAID',
    description: 'Skip the admin. Ship quotes, schedule fast, keep the bakkie moving. Built for SA conditions—works offline, perfect for load shedding.',
    buttonColor: '#f25c05',
    ghostName: 'OnSite',
    ghostTitle: 'Business Simplified',
    infoColor: '#f25c05',
    portfolio: 'onsite',
    url: 'https://onsite-theta.vercel.app/',
  },
  {
    id: 5,
    progressColor: '#ff6600',
    bgColor: '#ffffff',
    subTitle: 'COMPREHENSIVE SOLUTIONS',
    title: 'FINANCIAL SERVICES',
    description: 'Comprehensive financial and insurance solutions across South Africa. Serving SMEs with professionalism and integrity in all interactions.',
    buttonColor: '#1875ff',
    ghostName: 'WorkSite Solutions',
    ghostTitle: 'Insurance & More',
    infoColor: '#1875ff',
    portfolio: 'worksitesolutions',
    url: 'https://worksitesolutions.vercel.app/',
  },
  {
    id: 6,
    progressColor: '#ff6600',
    bgColor: '#00cc00',
    subTitle: 'BE SEEN SHOW & SELL',
    title: 'A2Z SELLR',
    description: 'The all-in-one home for South African sellers. Your products, your services, your brand—amplified with tools built for real SA businesses. Boost revenue by 80%.',
    buttonColor: '#22c55e',
    ghostName: 'A2Z Sellr',
    ghostTitle: 'Seller Platform',
    infoColor: '#22c55e',
    portfolio: 'a2zsellr',
    url: 'https://www.a2zsellr.life/',
  },
  {
    id: 7,
    progressColor: '#ff6600',
    bgColor: '#ffffff',
    subTitle: 'HEALTHCARE THAT WORKS FOR YOU',
    title: 'DAY1 HEALTH',
    description: 'Quality healthcare access for every South African. Choose a plan, apply online in 5 minutes, visit thousands of network providers, and start your cover from Day 1 with no waiting periods for accidents and emergency services.',
    buttonColor: '#16a34a',
    ghostName: 'Day1 Health',
    ghostTitle: 'Healthcare Coverage',
    infoColor: '#16a34a',
    portfolio: 'day1health',
    url: 'https://www.day1health.co.za/',
  },
  {
    id: 8,
    progressColor: '#ff6600',
    bgColor: '#ffffff',
    subTitle: 'DIGNIFIED FUNERAL SERVICES',
    title: 'KHAMBI',
    description: 'Compassionate and affordable funeral services that honor your loved ones with dignity. We handle every detail with care, from planning to execution, ensuring a respectful farewell during your time of need.',
    buttonColor: '#b48b49',
    ghostName: 'Khambi',
    ghostTitle: 'Funeral Services',
    infoColor: '#b48b49',
    portfolio: 'khambi',
    url: 'https://khambifunerals.com/',
  },
  {
    id: 9,
    progressColor: '#ff6600',
    bgColor: '#ffffff',
    subTitle: 'NATURAL GUT HEALTH',
    title: 'EUBIOSIS-S',
    description: 'Real Results. Eubiosis-S represents the perfect balance of your body\'s microbial ecosystem with 42 beneficial bacterial strains suspended in pure organic honey for maximum effectiveness.',
    buttonColor: '#3a9e92',
    ghostName: 'Eubiosis-S',
    ghostTitle: 'Gut Health Supplement',
    infoColor: '#3a9e92',
    portfolio: 'eubiosis',
    url: 'https://www.eubiosis.pro/',
  },
  {
    id: 10,
    progressColor: '#ff6600',
    bgColor: '#000000',
    subTitle: 'HONEST CAR DEALERSHIP',
    title: 'MAJESTIC CARS',
    description: 'Simple, honest, stress-free car buying. 100% inspected vehicles, fair pricing, and transparent service. Building trust one customer at a time with old-school values.',
    buttonColor: '#ff8c00',
    ghostName: 'Majestic Cars',
    ghostTitle: 'Modern Dealership',
    infoColor: '#ff8c00',
    portfolio: 'majestic-cars',
    url: 'https://majesticars.com/',
  },
]
